// I2CSlaveConstants.h

#ifndef _I2CSLAVECONSTANTS_h
#define _I2CSLAVECONSTANTS_h

#define I2C_BUFFER_SIZE								32
#define TWI_RX_BUFFER_SIZE							( I2C_BUFFER_SIZE )
#define TWI_TX_BUFFER_SIZE							( I2C_BUFFER_SIZE )

#define I2C_ADDRESS_MIN_VALUE						0x10
#define I2C_ADDRESS_MAX_VALUE						0xC0

#define I2C_SLAVE_BASE_HEADER						0xF0
#define I2C_SLAVE_MAX_HEADER_VALUE					( I2C_SLAVE_BASE_HEADER - 1)
#define I2C_SLAVE_BASE_HEADER_DEVICE_ID				( I2C_SLAVE_BASE_HEADER + 0)
#define I2C_SLAVE_BASE_HEADER_DEVICE_SERIAL			( I2C_SLAVE_BASE_HEADER + 1)
#define I2C_SLAVE_BASE_HEADER_MESSAGE_OVERFLOWS		( I2C_SLAVE_BASE_HEADER + 2)
#define I2C_SLAVE_BASE_HEADER_MESSAGE_BAD_SIZE		( I2C_SLAVE_BASE_HEADER + 3)
#define I2C_SLAVE_BASE_HEADER_MESSAGE_ERROR_CONTENT	( I2C_SLAVE_BASE_HEADER + 4)
//#define I2C_SLAVE_BASE_HEADER_HEALTH_REPORT			( I2C_SLAVE_BASE_HEADER + 3)


#if defined(__AVR_ATmega328P__)
#define I2C_MESSAGE_RECEIVER_QUEUE_DEFAULT_DEPTH	10
#elif defined(__AVR_ATtiny85__)
#define I2C_MESSAGE_RECEIVER_QUEUE_DEFAULT_DEPTH	3 //ATTiny has much less memory, we can't have such a big queue.
#define PIN_WIRE_SCL 7
#define PIN_WIRE_SDA 5
#endif

#endif

